<style>
  a[href="/account"] {
    display: none;
  }
  body {
    background-size: 5000px 2000px;
    background-position: top;
  }
  main {
    background-color: var(--body);
    box-shadow: 0 0 3px var(--opposite);
  	padding: 25px;
  	margin: 25px;
    border-radius: 20px;
  }
  main * {
    /* outline: 2px solid lightgreen; */
  }
  main form {
  	padding: 10px;
  	margin: 10px;
    align-items: center;
    text-align: center;
    justify-content: center;
    font-size: 0.8em;
    max-width: 950px;
  }
  main form * {
    margin: 5px 0;
  }
  main form h1 {
    text-align: center;
    flex-grow: 1;
  }
  main form div {
    display: block;
    overflow: hidden;
    outline: 2px solid var(--nav);
    border-radius: 10px;
  	padding-left: 10px;
    min-width: 0px;
    position: relative;
  }
  main form div i {
    top: 0;
    cursor: pointer;
    padding: 10px;
    position: absolute;
    top: -25%;
    right: 0;
    /*transform: translateY(-25%);*/
  }
  main form div :nth-child(3) {
    right: 1.7em;
  }
  main form div i:hover {
    background-color: var(--nav);
  }
  main form div i[data-show="show"]:before {
    display: block;
    content: '\e809';
  }
  main form div i[data-show="hide"]:before {
    display: block;
    content: '\e80d';
  }
  main form div input {
    min-width: 0px;
    width: 100%;
  }
  main form button {
    width: 100%;
    display: block;
    font-weight: 700;
    border-radius: 5px;
  	padding: 5px;
    background-color: var(--nav);
    cursor: pointer;
  }
  #switch-state:checked ~ #login {
    display: none;
  }
  #switch-state:not(:checked) ~ #register {
    display: none;
  }
  main form p {
  }
  main form p label {
    color: darkblue;
    cursor: pointer;
    padding: 5px 20px;
    border-radius: 10px;
    background-color: var(--opposite);
  }
</style>
<main>
  <input id="switch-state" type="checkbox" class="hide" />
  <form id="login">
    <h1>Login Form</h1>
    <div>
      <input type="text" placeholder="Username" name="u" require/>
      <i onclick="eraseInput(this)">&#xf1f8;</i>
    </div>
    <div>
      <input type="password" placeholder="Password" name="p" require/>
      <i onclick="eraseInput(this)">&#xf1f8;</i>
      <i data-show="show" onclick="showInput(this)"></i>
    </div>
    <button type="submit">Login</button>
    <p>create new account? <label for="switch-state">Register</label></p>
  </form>
  <form id="register">
    <h1>Register Form</h1>
    <div>
      <input type="text" placeholder="Username" name="u" require/>
      <i onclick="eraseInput(this)">&#xf1f8;</i>
    </div>
    <div>
      <input type="password" placeholder="Password" name="p" require/>
      <i onclick="eraseInput(this)">&#xf1f8;</i>
      <i data-show="show" onclick="showInput(this)">&#xe809;</i>
    </div>
    <div>
      <input type="password" placeholder="Retype Password" require/>
      <i onclick="eraseInput(this)">&#xf1f8;</i>
      <i data-show="show" onclick="showInput(this)">&#xe809;</i>
    </div>
    <button type="submit">Register</button>
    <p>have account? <label for="switch-state">Login</label></p>
  </form>
</main>
<script>
  function eraseInput (a) {
    a.parentElement.getElementsByTagName("input")[0].value = "";
  }
  function showInput (a) {
    if (a.dataset.show === "show") {
      a.dataset.show = "hide";
      a.parentElement.getElementsByTagName("input")[0].type = "text";
    } else if (a.dataset.show === "hide") {
      a.dataset.show = "show";
      a.parentElement.getElementsByTagName("input")[0].type = "password";
    }
  }
</script>