<style>
  body {
  	background-size: 2500px;
  	background-position: center;
  }
  header {
  	color: white;
  }
  header nav {
  	align-items: center;
  	justify-content: center;
  	text-align: center;
  	position: relative;
  	background-color: transparent;
  	box-shadow: none;
  	margin: 5px;
  	margin-top: 50px;
  }
  header nav a {
  	text-align: center;
    display: inline-block;
  	text-shadow: 2px 2px 2px black;
  }
  header nav a:first-child {
    flex: 1;
    order: -2;
    font-size: 2em;
  }
  header nav span#sp {
    display: none;
  }
  header nav #nav-search-switch {
    display: none;
  }
  header nav form {
    display: flex;
    order: -1;
    margin-bottom: 0;
    flex: 1 0 95%;
  }
  main {
    flex-grow: 1;
  }
  main {
    height: auto;
    margin: 10px 25px;
  }
  main a {
    border-radius: 15px;
  }
  main a:hover {
    background-color: var(--opposite);
  }
</style>
<main>
  <h5>
    <?php
      if (isset($_GET['s'])) {
        echo 'Search for: ' . $_GET['s'];
      } else {
        echo 'Hallo';
      }
    ?>
  </h5>
</main>