name: Test Server

on: [workflow_dispatch]

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  actions: write

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1